# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

# Flag for pyright to ignore type errors in this file.
# pyright: reportPrivateUsage=false

from __future__ import annotations

import logging
from collections.abc import Sequence
from typing import TYPE_CHECKING

import torch
import warp as wp
from isaaclab_physx.assets.articulation import Articulation
from isaaclab_physx.assets.kernels import split_state_to_root_pose_and_vel

import isaaclab.utils.string as string_utils
from isaaclab.utils.math import normalize, quat_apply, quat_apply_inverse

from isaaclab_contrib.actuators import Thruster
from isaaclab_contrib.utils.types import MultiRotorActions

from .multirotor_data import MultirotorData

if TYPE_CHECKING:
    from .multirotor_cfg import MultirotorCfg

# import logger
logger = logging.getLogger(__name__)

_BASE_BODY_INDEX = 0


class Multirotor(Articulation):
    """A multirotor articulation asset class.

    This class extends the base :class:`~isaaclab.assets.Articulation` class to support multirotor vehicles
    (such as quadcopters, hexacopters, and octocopters) with thruster actuators that apply forces
    at specific body locations. It is based on the implementation from :cite:t:`kulkarni2025aerialgym`.

    Unlike standard articulations that use joint-based control, multirotors are controlled through
    thrust forces generated by individual rotors/propellers. This class provides specialized functionality
    for managing multiple thruster actuators, computing combined wrenches from individual thrusts,
    and applying them to the multirotor's base link.

    Key Features:
        - **Thruster-based control**: Uses :class:`~isaaclab_contrib.actuators.Thruster` actuators
          instead of joint actuators for realistic rotor dynamics simulation.
        - **Force allocation**: Supports allocation matrices to convert individual thruster forces
          into combined body wrenches (forces and torques).
        - **Asymmetric dynamics**: Thruster actuators can model asymmetric rise/fall dynamics
          that reflect real motor behavior.
        - **Flexible configuration**: Supports arbitrary numbers and arrangements of thrusters
          through regex-based thruster naming patterns.

    Usage Example:
        .. code-block:: python

            import isaaclab.sim as sim_utils
            from isaaclab_contrib.assets import MultirotorCfg
            from isaaclab_contrib.actuators import ThrusterCfg

            # Define thruster actuator configuration
            thruster_cfg = ThrusterCfg(
                thruster_names_expr=["rotor_[0-3]"],  # Match rotors 0-3
                thrust_range=(0.0, 10.0),  # Min and max thrust in Newtons
                rise_time_constant=0.1,  # Time constant for thrust increase
                fall_time_constant=0.2,  # Time constant for thrust decrease
            )

            # Create multirotor configuration
            multirotor_cfg = MultirotorCfg(
                prim_path="/World/envs/env_.*/Robot",
                spawn=sim_utils.UsdFileCfg(usd_path="path/to/quadcopter.usd"),
                actuators={"thrusters": thruster_cfg},
                allocation_matrix=[  # 6x4 matrix for quadcopter (6 DOF, 4 thrusters)
                    [1.0, 1.0, 1.0, 1.0],  # Total vertical force
                    [0.0, 0.0, 0.0, 0.0],  # Lateral force (x)
                    [0.0, 0.0, 0.0, 0.0],  # Lateral force (y)
                    [0.0, 0.1, 0.0, -0.1],  # Roll torque
                    [-0.1, 0.0, 0.1, 0.0],  # Pitch torque
                    [0.01, -0.01, 0.01, -0.01],  # Yaw torque
                ],
            )

            # Create the multirotor instance
            multirotor = multirotor_cfg.class_type(multirotor_cfg)

    .. note::
        The allocation matrix maps individual thruster forces to a 6D wrench (3 forces + 3 torques)
        applied to the base link. The matrix dimensions should be (6, num_thrusters).

    .. seealso::
        - :class:`~isaaclab.assets.Articulation`: Base articulation class
        - :class:`MultirotorCfg`: Configuration class for multirotors
        - :class:`MultirotorData`: Data container for multirotor state
        - :class:`~isaaclab_contrib.actuators.Thruster`: Thruster actuator model
    """

    cfg: MultirotorCfg
    """Configuration instance for the multirotor."""

    actuators: dict[str, Thruster]
    """Dictionary of thruster actuator instances for the multirotor.

    The keys are the actuator names and the values are the actuator instances. The actuator instances
    are initialized based on the actuator configurations specified in the :attr:`MultirotorCfg.actuators`
    attribute. They are used to compute the thruster commands during the :meth:`write_data_to_sim` function.
    """

    def __init__(self, cfg: MultirotorCfg):
        """Initialize the multirotor articulation.

        Args:
            cfg: A configuration instance.
        """
        super().__init__(cfg)

    """
    Properties
    """

    @property
    def data(self) -> MultirotorData:
        return self._data

    @property
    def thruster_names(self) -> list[str]:
        """Ordered names of thrusters in the multirotor.

        This property aggregates thruster names from all thruster actuator groups configured
        for the multirotor. The names are ordered according to their array indices, which is
        important for setting thrust targets and interpreting thruster data.

        Returns:
            A list of thruster names in order. Returns an empty list if actuators are not yet initialized.

        Raises:
            ValueError: If a non-thruster actuator is found in the multirotor actuators.
        """
        if not hasattr(self, "actuators") or not self.actuators:
            return []

        thruster_names = []
        for actuator in self.actuators.values():
            if hasattr(actuator, "thruster_names"):
                thruster_names.extend(actuator.thruster_names)
            else:
                raise ValueError("Non thruster actuator found in multirotor actuators. Not supported at the moment.")

        return thruster_names

    @property
    def num_thrusters(self) -> int:
        """Number of thrusters in the multirotor.

        Returns:
            Total number of thrusters across all actuator groups.
        """
        return len(self.thruster_names)

    @property
    def allocation_matrix(self) -> torch.Tensor:
        """Allocation matrix for control allocation.

        The allocation matrix maps individual thruster forces to a 6D wrench vector
        (3 forces + 3 torques) applied to the base link. This allows converting
        per-thruster commands into the resulting body-frame forces and moments.

        The matrix has shape (6, num_thrusters), where:
            - Rows 0-2: Force contributions in body frame (Fx, Fy, Fz)
            - Rows 3-5: Torque contributions in body frame (Tx, Ty, Tz)

        Returns:
            Allocation matrix as a torch tensor on the device.
        """
        if self.cfg.allocation_matrix is None:
            raise RuntimeError(
                "Allocation matrix is None. This should have been computed during initialization. "
                "Please check that _compute_allocation_matrix() was called."
            )
        return torch.tensor(self.cfg.allocation_matrix, device=self.device, dtype=torch.float32)

    """
    Operations
    """

    def set_thrust_target(
        self,
        target: torch.Tensor,
        thruster_ids: Sequence[int] | slice | None = None,
        env_ids: Sequence[int] | None = None,
    ):
        """Set target thrust values for thrusters.

        This method sets the desired thrust values for specific thrusters in specific environments.
        The thrust targets are stored and later processed by the thruster actuator models during
        the :meth:`write_data_to_sim` call. The actuator models may apply dynamics (rise/fall times)
        and constraints (thrust limits) to these targets.

        Args:
            target: Target thrust values [N]. Shape is (num_envs, num_thrusters) or (num_envs,).
            thruster_ids: Indices of thrusters to set. Defaults to None (all thrusters).
                Can be a sequence of integers, a slice, or None.
            env_ids: Environment indices to set. Defaults to None (all environments).
                Can be a sequence of integers or None.

        Example:
            .. code-block:: python

                # Set thrust for all thrusters in all environments
                multirotor.set_thrust_target(torch.ones(num_envs, 4) * 5.0)

                # Set thrust for specific thrusters
                multirotor.set_thrust_target(
                    torch.tensor([[5.0, 6.0]]),  # Different thrust for 2 thrusters
                    thruster_ids=[0, 2],  # Apply to thrusters 0 and 2
                    env_ids=[0],  # Only in environment 0
                )
        """
        # resolve indices
        if env_ids is None:
            env_ids = slice(None)
        if thruster_ids is None:
            thruster_ids = slice(None)

        # broadcast env_ids if needed to allow double indexing
        if env_ids != slice(None) and thruster_ids != slice(None):
            env_ids = env_ids[:, None]

        # set targets
        self.data.thrust_target[env_ids, thruster_ids] = target

    def reset(self, env_ids: Sequence[int] | None = None):
        """Reset the multirotor to default state.

        This method resets both the base articulation state (pose, velocities) and
        multirotor-specific state (thruster targets) to their default values as specified
        in the configuration.

        Args:
            env_ids: Environment indices to reset. Defaults to None (all environments).
                Can be a sequence of integers or None.

        Note:
            The default thruster state is set via the :attr:`MultirotorCfg.init_state.rps`
            configuration parameter.
        """
        # call parent reset
        super().reset(env_ids)

        # reset multirotor-specific data
        if env_ids is None:
            env_ids = self._ALL_INDICES
        if isinstance(env_ids, wp.array):
            env_ids = wp.to_torch(env_ids)
        elif not isinstance(env_ids, torch.Tensor):
            env_ids = torch.tensor(env_ids, dtype=torch.long, device=self.device)

        # reset thruster targets to default values
        if self.data.thrust_target is not None and self.data.default_thruster_rps is not None:
            self.data.thrust_target[env_ids] = (
                self.actuators["thrusters"].thrust_const[env_ids] * self.data.default_thruster_rps[env_ids] ** 2
            )

    def write_data_to_sim(self):
        """Write thrust commands and external wrenches to the simulation.

        Thruster forces are combined through the allocation matrix, applied through the
        instantaneous wrench composer, and merged with any permanent external wrenches
        before being written to PhysX.
        """
        self._apply_actuator_model()
        self._combine_thrusts()
        self._apply_combined_wrench_to_composer()
        self._apply_drag()
        self._write_external_wrenches_to_sim()
        self._instantaneous_wrench_composer.reset()

    """
    Internal methods
    """

    def _create_buffers(self):
        # Replace data container with MultirotorData
        self._data = MultirotorData(self.root_view, self.device)
        super()._create_buffers()
        # Create thruster buffers with correct size
        self._create_thruster_buffers()

        self._base_body_ids = torch.tensor([_BASE_BODY_INDEX], dtype=torch.long, device=self.device)

    def _create_thruster_buffers(self):
        """Create thruster buffers with correct size."""
        num_instances = self.num_instances

        self._thruster_body_mapping = {}
        all_thruster_names = []
        for actuator_name, actuator_cfg in self.cfg.actuators.items():
            if not hasattr(actuator_cfg, "thruster_names_expr"):
                continue

            body_indices, thruster_names = self.find_bodies(actuator_cfg.thruster_names_expr, preserve_order=True)
            start_idx = len(all_thruster_names)
            thruster_array_indices = list(range(start_idx, start_idx + len(body_indices)))
            all_thruster_names.extend(thruster_names)
            self._thruster_body_mapping[actuator_name] = {
                "body_indices": body_indices,
                "array_indices": thruster_array_indices,
                "thruster_names": thruster_names,
            }

        num_thrusters = len(all_thruster_names)
        if num_thrusters == 0:
            raise ValueError(
                "No thrusters found in actuator configuration. "
                "Please check 'thruster_names_expr' in the provided 'MultirotorCfg.actuators' configuration."
            )

        # Create thruster data tensors with correct size
        self.data.default_thruster_rps = torch.zeros(num_instances, num_thrusters, device=self.device)
        # thrust after controller and allocation is applied
        self.data.thrust_target = torch.zeros(num_instances, num_thrusters, device=self.device)
        self.data.computed_thrust = torch.zeros(num_instances, num_thrusters, device=self.device)
        self.data.applied_thrust = torch.zeros(num_instances, num_thrusters, device=self.device)

        # Combined wrench buffers
        self._thrust_target_sim = torch.zeros_like(self.data.thrust_target)  # thrust after actuator model is applied
        # wrench target for combined mode
        self._internal_wrench_target_sim = torch.zeros(num_instances, 6, device=self.device)
        # internal force/torque targets per body for combined mode
        self._internal_force_target_sim = torch.zeros(num_instances, self.num_bodies, 3, device=self.device)
        self._internal_torque_target_sim = torch.zeros(num_instances, self.num_bodies, 3, device=self.device)

        self.data.thruster_names = all_thruster_names

    def _process_cfg(self):
        """Post-processing of multirotor configuration parameters."""
        default_root_state = (
            tuple(self.cfg.init_state.pos)
            + tuple(self.cfg.init_state.rot)
            + tuple(self.cfg.init_state.lin_vel)
            + tuple(self.cfg.init_state.ang_vel)
        )
        default_root_state = torch.tensor(default_root_state, dtype=torch.float, device=self.device)
        default_root_state = default_root_state.repeat(self.num_instances, 1)
        default_root_state_wp = wp.from_torch(default_root_state, dtype=wp.float32)
        pose_output = wp.zeros(self.num_instances, dtype=wp.transformf, device=self.device)
        vel_output = wp.zeros(self.num_instances, dtype=wp.spatial_vectorf, device=self.device)
        wp.launch(
            split_state_to_root_pose_and_vel,
            dim=self.num_instances,
            inputs=[default_root_state_wp],
            outputs=[pose_output, vel_output],
            device=self.device,
        )
        self.data.default_root_pose = pose_output
        self.data.default_root_vel = vel_output

        # Handle thruster-specific initial state
        if hasattr(self.data, "default_thruster_rps") and hasattr(self.cfg.init_state, "rps"):
            # Match against thruster names
            indices_list, _, values_list = string_utils.resolve_matching_names_values(
                self.cfg.init_state.rps, self.data.thruster_names
            )
            if indices_list:
                rps_values = torch.tensor(values_list, device=self.device)
                self.data.default_thruster_rps[:, indices_list] = rps_values

    def _process_actuators_cfg(self):
        """Override parent method to do nothing - we handle thrusters separately."""
        # We handle thruster processing in _process_thruster_cfg()
        self._process_thruster_cfg()

        # We compute the allocation matrix after resolving thruster names and mappings
        if self.cfg.allocation_matrix is None:
            self._compute_allocation_matrix()

    def _process_thruster_cfg(self):
        """Process and apply multirotor thruster properties."""
        # create actuators
        self.actuators = dict()
        self._has_implicit_actuators = False

        # Check for mixed configurations (same as before)
        has_thrusters = False
        has_joints = False

        for actuator_name, actuator_cfg in self.cfg.actuators.items():
            if hasattr(actuator_cfg, "thruster_names_expr"):
                has_thrusters = True
            elif hasattr(actuator_cfg, "joint_names_expr"):
                has_joints = True

        if has_thrusters and has_joints:
            raise ValueError("Mixed configurations with both thrusters and regular joints are not supported.")

        if has_joints:
            raise ValueError("Regular joint actuators are not supported in Multirotor class.")

        for actuator_name, actuator_cfg in self.cfg.actuators.items():
            mapping = self._thruster_body_mapping[actuator_name]
            body_indices = mapping["body_indices"]
            thruster_array_indices = mapping["array_indices"]
            thruster_names = mapping["thruster_names"]

            # Create thruster actuator
            actuator: Thruster = actuator_cfg.class_type(
                cfg=actuator_cfg,
                thruster_names=thruster_names,
                thruster_ids=thruster_array_indices,
                num_envs=self.num_instances,
                device=self.device,
                init_thruster_rps=self.data.default_thruster_rps[:, thruster_array_indices],
            )

            # Store actuator and initialize its force target from the actuator state
            self.actuators[actuator_name] = actuator
            self.data.thrust_target[:, thruster_array_indices] = actuator.curr_thrust

            # Log information
            logger.info(
                f"Thruster actuator: {actuator_name} with model '{actuator_cfg.class_type.__name__}'"
                f" (thruster names: {thruster_names} [{body_indices}])."
            )

        # Log summary
        logger.info(f"Initialized {len(self.actuators)} thruster actuator(s) for multirotor.")

    def _apply_actuator_model(self):
        """Processes thruster commands for the multirotor by forwarding them to the actuators.

        This internal method iterates through all thruster actuator groups and applies their
        respective actuator models to the thrust targets. The actuator models simulate realistic
        motor dynamics including:

        - Rise/fall time constants for asymmetric response
        - Thrust saturation and clipping to physical limits
        - Integration of motor dynamics over time

        The computed thrust values are stored in internal buffers for subsequent wrench computation.

        Note:
            This method updates:
            - :attr:`_thrust_target_sim`: Processed thrust values after actuator model
            - :attr:`_data.computed_thrust`: Thrust before saturation
            - :attr:`_data.applied_thrust`: Final thrust after saturation
        """

        # process thruster actions per group
        for actuator in self.actuators.values():
            if not isinstance(actuator, Thruster):
                continue

            # prepare input for actuator model based on cached data
            control_action = MultiRotorActions(
                thrusts=self.data.thrust_target[:, actuator.thruster_indices],
                thruster_indices=actuator.thruster_indices,
            )

            # compute thruster command from the actuator model
            control_action = actuator.compute(control_action)

            # update targets (these are set into the simulation)
            if control_action.thrusts is not None:
                self._thrust_target_sim[:, actuator.thruster_indices] = control_action.thrusts

            # update state of the actuator model
            self.data.computed_thrust[:, actuator.thruster_indices] = actuator.computed_thrust
            self.data.applied_thrust[:, actuator.thruster_indices] = actuator.applied_thrust

    def _apply_combined_wrench_to_composer(self):
        """Add the allocation-matrix wrench to the instantaneous wrench composer."""
        forces = self._internal_force_target_sim[:, _BASE_BODY_INDEX, :]
        torques = self._internal_torque_target_sim[:, _BASE_BODY_INDEX, :]

        com_pos_b = self._compute_articulation_com()
        base_com_pos_b = self.data.body_com_pos_b.torch[0, _BASE_BODY_INDEX, :]
        r_com_offset = com_pos_b - base_com_pos_b

        extra_torque = torch.cross(
            r_com_offset.unsqueeze(0).expand(self.num_instances, -1),
            forces,
            dim=1,
        )
        torques_corrected = torques - extra_torque

        positions = com_pos_b.unsqueeze(0).unsqueeze(0).expand(self.num_instances, 1, -1)
        self.instantaneous_wrench_composer.add_forces_and_torques_index(
            forces=forces.unsqueeze(1),
            torques=torques_corrected.unsqueeze(1),
            positions=positions,
            body_ids=self._base_body_ids,
            is_global=False,
        )

    def _apply_drag(self):
        """Apply aerodynamic drag through the instantaneous wrench composer."""
        if (
            self.cfg.lin_drag_linear_coef == 0.0
            and self.cfg.lin_drag_quadratic_coef == 0.0
            and self.cfg.ang_drag_linear_coef == 0.0
            and self.cfg.ang_drag_quadratic_coef == 0.0
        ):
            return

        lin_vel_w = self.data.body_link_lin_vel_w.torch[:, _BASE_BODY_INDEX, :]
        ang_vel_w = self.data.body_link_ang_vel_w.torch[:, _BASE_BODY_INDEX, :]
        link_quat_w = self.data.body_link_quat_w.torch[:, _BASE_BODY_INDEX, :]
        ang_vel_b = quat_apply_inverse(link_quat_w, ang_vel_w)

        lin_vel_norm = torch.linalg.vector_norm(lin_vel_w, dim=-1, keepdim=True)
        lin_drag = (
            -self.cfg.lin_drag_linear_coef * lin_vel_w - self.cfg.lin_drag_quadratic_coef * lin_vel_norm * lin_vel_w
        )

        ang_vel_norm = torch.linalg.vector_norm(ang_vel_b, dim=-1, keepdim=True)
        ang_drag_b = (
            -self.cfg.ang_drag_linear_coef * ang_vel_b - self.cfg.ang_drag_quadratic_coef * ang_vel_norm * ang_vel_b
        )
        ang_drag_w = quat_apply(link_quat_w, ang_drag_b)

        positions = self.data.body_com_pos_w.torch[:, _BASE_BODY_INDEX : _BASE_BODY_INDEX + 1, :3]
        self.instantaneous_wrench_composer.add_forces_and_torques_index(
            forces=lin_drag.unsqueeze(1),
            torques=ang_drag_w.unsqueeze(1),
            positions=positions,
            body_ids=self._base_body_ids,
            is_global=True,
        )

    def _write_external_wrenches_to_sim(self):
        """Compose and apply pending external wrenches to the simulation.

        Matches :meth:`isaaclab_physx.assets.articulation.Articulation.write_data_to_sim`.
        Articulation does not cache RigidObject-style ``_get_inst_wrench_*`` views.
        """
        if self._instantaneous_wrench_composer.active or self._permanent_wrench_composer.active:
            if self._instantaneous_wrench_composer.active:
                composer = self._instantaneous_wrench_composer
                composer.add_raw_buffers_from(self._permanent_wrench_composer)
            else:
                composer = self._permanent_wrench_composer
            composer.compose_to_body_frame()
            self.root_view.apply_forces_and_torques_at_position(
                force_data=composer.out_force_b.warp.flatten().view(wp.float32),
                torque_data=composer.out_torque_b.warp.flatten().view(wp.float32),
                position_data=None,
                indices=self._ALL_INDICES,
                is_global=False,
            )

    def _compute_allocation_matrix(self):
        """Compute the allocation matrix from USD geometry and thruster configuration."""
        if self.cfg.rotor_directions is None:
            raise ValueError(
                "Cannot compute allocation matrix: rotor_directions must be provided "
                "in config when allocation_matrix is not specified."
            )

        rotor_directions = self.cfg.rotor_directions
        cq = 0.0
        if "thrusters" in self.cfg.actuators:
            cq = self.cfg.actuators["thrusters"].torque_to_thrust_ratio

        thruster_names_expr = self.cfg.actuators["thrusters"].thruster_names_expr
        _, thruster_names = self.find_bodies(thruster_names_expr, preserve_order=True)
        num_thrusters = len(thruster_names)

        if len(rotor_directions) != num_thrusters:
            raise ValueError(
                f"Cannot compute allocation matrix: number of rotor_directions ({len(rotor_directions)}) "
                f"must match number of thrusters ({num_thrusters})"
            )

        base_link_ids, _ = self.find_bodies("base_link", preserve_order=True)
        if len(base_link_ids) == 0:
            raise ValueError("Cannot compute allocation matrix: could not find 'base_link' in articulation")
        base_link_id = base_link_ids[0]

        self.update(dt=0.0)

        base_pos_w = self.data.body_link_pos_w.torch[0, base_link_id, :]
        base_quat_w = self.data.body_link_quat_w.torch[0, base_link_id, :]
        com_pos_b = self._compute_articulation_com()
        logger.info(f"Computed full articulation COM in base_link frame: {com_pos_b}")

        allocation_matrix = torch.zeros(6, num_thrusters, device=self.device)
        thrust_dir_local = torch.tensor(self.cfg.thruster_force_direction, device=self.device, dtype=torch.float32)
        thrust_dir_local = normalize(thrust_dir_local.unsqueeze(0)).squeeze(0)

        for i, thruster_name in enumerate(thruster_names):
            thruster_body_ids, _ = self.find_bodies(thruster_name, preserve_order=True)
            if len(thruster_body_ids) == 0:
                thruster_body_ids, _ = self.find_bodies(f".*{thruster_name}.*", preserve_order=True)
            if len(thruster_body_ids) == 0:
                raise ValueError(
                    f"Cannot compute allocation matrix: could not find body for thruster '{thruster_name}'"
                )

            thruster_body_id = thruster_body_ids[0]
            thruster_com_pos_w = self.data.body_com_pos_w.torch[0, thruster_body_id, :3]
            thruster_quat_w = self.data.body_link_quat_w.torch[0, thruster_body_id, :]

            thruster_com_pos_rel_w = thruster_com_pos_w - base_pos_w
            thruster_com_pos_b = quat_apply_inverse(base_quat_w, thruster_com_pos_rel_w)
            thruster_pos_com_b = thruster_com_pos_b - com_pos_b

            thrust_dir_w = quat_apply(thruster_quat_w, thrust_dir_local)
            thrust_dir_b = quat_apply_inverse(base_quat_w, thrust_dir_w)
            thrust_dir_b = normalize(thrust_dir_b.unsqueeze(0)).squeeze(0)

            allocation_matrix[0:3, i] = thrust_dir_b
            torque_from_force = torch.linalg.cross(thruster_pos_com_b, thrust_dir_b)
            alpha_i = float(rotor_directions[i])
            rotor_torque = -alpha_i * cq * thrust_dir_b
            allocation_matrix[3:6, i] = torque_from_force + rotor_torque

        self.cfg.allocation_matrix = allocation_matrix.cpu().numpy().tolist()
        logger.info(f"Computed allocation matrix from USD file: {num_thrusters} thrusters")

    def _compute_articulation_com(self) -> torch.Tensor:
        """Compute the center of mass of the entire articulation in the base link frame.

        Returns:
            COM position in the base link frame [m]. Shape is (3,).
        """
        base_link_ids, _ = self.find_bodies("base_link", preserve_order=True)
        if len(base_link_ids) == 0:
            raise ValueError("Cannot compute articulation COM: could not find 'base_link' in articulation")
        base_link_id = base_link_ids[0]

        base_pos_w = self.data.body_link_pos_w.torch[0, base_link_id, :]
        base_quat_w = self.data.body_link_quat_w.torch[0, base_link_id, :]
        body_com_pos_w = self.data.body_com_pos_w.torch[0, :, :3]
        body_masses = self.data.body_mass.torch[0, :]

        total_mass = torch.sum(body_masses)
        if total_mass < 1e-6:
            raise ValueError("Cannot compute articulation COM: total mass is too small or zero")

        com_pos_w = torch.einsum("i,ij->j", body_masses, body_com_pos_w) / total_mass
        com_pos_rel_w = com_pos_w - base_pos_w
        return quat_apply_inverse(base_quat_w, com_pos_rel_w)

    def _combine_thrusts(self):
        """Combine individual thrusts into a wrench vector.

        This internal method uses the allocation matrix to convert individual thruster
        forces into a 6D wrench vector (3D force + 3D torque) in the body frame. The
        wrench is then assigned to the base link (body index 0) for application to
        the simulation.

        The allocation matrix encodes the geometric configuration of the thrusters,
        including their positions and orientations relative to the center of mass.

        Mathematical operation:
            wrench = allocation_matrix @ thrusts
            where wrench = [Fx, Fy, Fz, Tx, Ty, Tz]^T
        """
        thrusts = self._thrust_target_sim
        self._internal_wrench_target_sim = (self.allocation_matrix @ thrusts.T).T
        self._internal_force_target_sim[:, _BASE_BODY_INDEX, :] = self._internal_wrench_target_sim[:, :3]
        self._internal_torque_target_sim[:, _BASE_BODY_INDEX, :] = self._internal_wrench_target_sim[:, 3:]

    def _validate_cfg(self):
        """Validate the multirotor configuration after processing.

        Note:
            This function should be called only after the configuration has been processed and the buffers have been
            created. Otherwise, some settings that are altered during processing may not be validated.
        """
        # Only validate if actuators have been created
        if hasattr(self, "actuators") and self.actuators:
            # Validate thruster-specific configuration
            for actuator_name in self.actuators:
                if isinstance(self.actuators[actuator_name], Thruster):
                    initial_thrust = self.actuators[actuator_name].curr_thrust
                    # check that the initial thrust is within the limits
                    thrust_limits = self.actuators[actuator_name].cfg.thrust_range
                    if torch.any(initial_thrust < thrust_limits[0]) or torch.any(initial_thrust > thrust_limits[1]):
                        raise ValueError(
                            f"Initial thrust for actuator '{actuator_name}' is out of bounds: "
                            f"{initial_thrust} not in {thrust_limits}"
                        )

    def _log_articulation_info(self):
        """Log information about the articulation."""
        super()._log_articulation_info()

        # Exclusive data from Multirotor
        logger.info(f"Multirotor initialized with {self.num_thrusters} thrusters")
        logger.info(f"Thruster names: {self.thruster_names}")
        logger.info(f"Thruster force direction: {self.cfg.thruster_force_direction}")
